/** Internal error codes surfaced in logs / API responses. Never include secrets. */
export const ErrorCodes = {
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_DISABLED: 'AUTH_DISABLED',
  KEY_INVALID: 'KEY_INVALID',
  KEY_EXPIRED: 'KEY_EXPIRED',
  DEVICE_LIMIT: 'DEVICE_LIMIT',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UPSTREAM_TIMEOUT: 'UPSTREAM_TIMEOUT',
  UPSTREAM_404: 'UPSTREAM_404',
  UPSTREAM_4XX: 'UPSTREAM_4XX',
  UPSTREAM_5XX: 'UPSTREAM_5XX',
  UPSTREAM_UNREACHABLE: 'UPSTREAM_UNREACHABLE',
  /** Upstream uses a port Cloudflare Workers cannot open a subrequest to. */
  UNSUPPORTED_PORT: 'UNSUPPORTED_PORT',
  INVALID_HLS: 'INVALID_HLS',
  UNSAFE_URL: 'UNSAFE_URL',
  DB_ERROR: 'DB_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PLAYLIST_SYNC_FAILED: 'PLAYLIST_SYNC_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  ADMIN_DISABLED: 'ADMIN_DISABLED',
  BAD_REQUEST: 'BAD_REQUEST',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
